#!/bin/bash
#
##SBATCH --job-name="h5synapses"
#SBATCH --time=01:00:00
#SBATCH --account=proj16
#SBATCH --partition=debug
#SBATCH --nodes=256
##SBATCH --ntasks-per-node=2
##SBATCH --cpus-per-task=4
#SBATCH --exclusive
#SBATCH --output=out.%j.out
#SBATCH --error=out.%j.err
 
#======START=====
module load slurm

#source ~/nestio/nest-2.6.0-install/bin/nest_vars.sh
source ~/nestio/install/nest_ambm/bin/nest_vars.sh

# module on viz cluster
 
export OMP_NUM_THREADS=8

#time srun nest Potjans2014Params.sli 

module load totalview
totalview -args srun -n 200 nest Potjans2014Params.sli
