#!/bin/bash
#
##SBATCH --job-name="fullmouse"
#SBATCH --time=10:00:00
#SBATCH --account=proj16
#SBATCH --partition=prod-large
#SBATCH --nodes=4k
#SBATCH --ntasks-per-node=1
##SBATCH --cpus-per-task=4
#SBATCH --exclusive
#SBATCH --output=out.%j.out
#SBATCH --error=out.%j.err
 
#======START=====
module load slurm

source /gpfs/bbp.cscs.ch/home/schumann/nestio/install/nest_ambm/bin/nest_vars.sh
export OMP_NUM_THREADS=8
 
time srun nest full.sli 
