#!/bin/bash
#
##SBATCH --job-name="fullmouse"
#SBATCH --time=1:00:00
#SBATCH --account=proj16
#SBATCH --partition=debug
#SBATCH --nodes=256
#SBATCH --ntasks-per-node=1
##SBATCH --cpus-per-task=4
#SBATCH --exclusive
#SBATCH --output=out.%j.out
#SBATCH --error=out.%j.err
 
#======START=====
module load slurm

source /gpfs/bbp.cscs.ch/home/schumann/nestio/install/nest_ambm/bin/nest_vars.sh
export OMP_NUM_THREADS=16
 
#time srun nest run.sli 

module load totalview
totalview -args srun nest run.sli

